### ISSUE TITLE
modeling.py visualization_prediction code

### ISSUE THREAD

**Issue by GXMT** [maximkiesel1/Stock_Market_Prediction#1]
# Print the predicted stock prices for the selected days and a trading recommendation
        print('')
        print('The predicted Adjusted Close for day 7 is: {}'.format(round(prediction[name]['selected_days'][0], 2)))
        print('The predicted Adjusted Close for day 14 is: {}'.format(round(prediction[name]['selected_days'][1], 2)))
        print('The predicted Adjusted Close for day 28 is: {}'.format(round(prediction[name]['selected_days'][0], 2)))

'selected_days'[0] is apearing at day 28. isn't it [2]?

**Comment by maximkiesel1** [comment]
You are right. Thanks for the hint.
